import { readFileSync } from "node:fs";
import { decodeBlueprintString, normaliseEntities, type GameData } from "@factoriotools/engine";
import { beltSpecResolver, buildBeltNetwork } from "../src/index.js";
const data = JSON.parse(readFileSync("../../apps/site/public/data/game-data.json", "utf8")) as GameData;
const env = decodeBlueprintString(readFileSync("/tmp/claude-0/-home-user-FactorioTools/856d0c06-9b57-50c9-bd51-bdca4ba46b4c/scratchpad/user-bp.txt", "utf8").trim());
console.log(env.blueprint?.label, env.blueprint?.version);
const ents = normaliseEntities(env.blueprint!);
const count: Record<string, number> = {}; for (const e of ents) count[e.name] = (count[e.name] ?? 0) + 1; console.log(count);
const ug = ents.filter((e) => e.name.includes("underground"));
console.log(ug.slice(0, 12).map((e) => `${e.name} ${e.x},${e.y} d${e.direction} ${e.undergroundType}`).join("\n"));
const net = buildBeltNetwork(ents, beltSpecResolver(data));
const ugNodes = net.nodes.filter((n) => n.kind.startsWith("underground"));
console.log("ug nodes", ugNodes.length, "paired", ugNodes.filter((n) => n.pair).length);
console.log("ports in", net.ports.filter((p) => p.kind === "input").length, "out", net.ports.filter((p) => p.kind === "output").length, "lines", net.lines.length);
const raw = env.blueprint!.entities!.filter((e) => e.name.includes("underground")).slice(0, 4); console.log(JSON.stringify(raw));
